#!/bin/sh

. /usr/lib/live/config.sh
. /etc/os-release

## live-config(7) - System Configuration Components
## Copyright (C) 2016-2020 The Debian Live team
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
## Copyright (C) 2025 MiniOS <https://minios.dev>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.

#set -e

Cmdline() {
    # Reading kernel command line
    for _PARAMETER in ${LIVE_CONFIG_CMDLINE}; do
        case "${_PARAMETER}" in
        live-config.username=* | username=*)
            LIVE_USERNAME="${_PARAMETER#*username=}"
            ;;
        esac
    done
}

Init() {
    # Checking if package is installed or already configured
    if component_was_executed "issue-setup"; then
        exit 0
    fi

    echo -n " issue-setup"
}

Config() {
    # Base banner
    cat <<EOF >/etc/issue


                                                                          \\l





                        Thank you for using MiniOS.
EOF

    # Append distribution info
    case "$ID" in
    debian)
        DIST="Based on [1;31mDebian GNU/Linux[0;29m."
        ;;
    ubuntu)
        DIST="Based on [1;38;5;214mUbuntu[0;29m."
        ;;
    kali)
        DIST="Based on [1;36mKali Linux[0;29m."
        ;;
    *)
        DIST=""
        ;;
    esac

    [ -n "$DIST" ] && printf "                        %s\n" "$DIST" >>"/etc/issue"

    # Append Slax info if installed
    if pkg_is_installed "fluxbox-slax" || pkg_is_installed "fluxbox-flux"; then
        printf "                        With [1;32mSlax[0;29m flavour.\n" >>"/etc/issue"
    fi

    # Append ASCII art
    cat >>"/etc/issue" <<'EOF'

    [1;1m::::    ::::  ::::::::::: ::::    ::: ::::::::::: ::::::::   ::::::::  [0;29m
    [1;1m+:+:+: :+:+:+     :+:     :+:+:   :+:     :+:    :+:    :+: :+:    :+: [0;29m
    [1;1m+:+ +:+:+ +:+     +:+     :+:+:+  +:+     +:+    +:+    +:+ +:+        [0;29m
    [1;1m+#+  +:+  +#+     +#+     +#+ +:+ +#+     +#+    +#+    +:+ +#++:++#++ [0;29m
    [1;1m+#+       +#+     +#+     +#+  +#+#+#     +#+    +#+    +#+        +#+ [0;29m
    [1;1m#+#       #+#     #+#     #+#   #+#+#     #+#    #+#    #+# #+#    #+# [0;29m
    [1;1m###       ### ########### ###    #### ########### ########   ########  [0;29m

EOF

    if [ "$LIVE_USERNAME" = "root" ]; then
        cat <<EOF >>/etc/issue
                            Default password:
                              root: [1;33mtoor[0;29m







EOF
    else
        cat <<EOF >>/etc/issue
                            Default passwords:
                              root: [1;33mtoor[0;29m
                              live: [1;33mevil[0;29m






EOF
    fi

    # Creating state file
    touch /var/lib/live/config/issue-setup
}

Init
Config
