#!/bin/sh

. /usr/lib/live/config.sh

## live-config(7) - System Configuration Components
## Copyright (C) 2016-2020 The Debian Live team
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.

#set -e

Init() {
    # Checking if package is installed or already configured
    if { [ ! -f "/usr/lib/systemd/system/xorg.service" ] && [ ! -f "/etc/init.d/minios-xorg" ]; } ||
        [ ! -x "/usr/bin/start-xorg.sh" ] ||
        component_was_executed "xorg-service"; then
        exit 0
    fi

    echo -n " xorg-service"
}

Config() {
    case "${LIVE_CONFIG_CMDLINE}" in
    *live-config.x11-mode=hardened* | *x11-mode=hardened*)
        if [ -f /usr/bin/start-xorg.sh ]; then
            sed -i 's/[[:space:]]-ac\([[:space:]]\|"\)/\1/g' /usr/bin/start-xorg.sh
        fi
        if [ -f /etc/X11/Xwrapper.config ]; then
            sed -i \
                -e 's|^allowed_users=.*|allowed_users=console|' \
                -e 's|^needs_root_rights=.*|needs_root_rights=auto|' \
                /etc/X11/Xwrapper.config
        fi
        ;;
    esac

    # Avoid xinit
    touch /var/lib/live/config/xinit

    # Creating state file
    touch /var/lib/live/config/xorg-service
}

Init
Config
