#!/bin/sh

. /usr/lib/live/config.sh

## live-config(7) - System Configuration Components
## Copyright (C) 2016-2020 The Debian Live team
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


#set -e

Cmdline ()
{
	# Reading kernel command line
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done
}

Init ()
{
	# Checking if package is installed or already configured
	if ! pkg_is_installed "gnome-screensaver" || \
	   component_was_executed "gnome-screensaver"
	then
		exit 0
	fi

	echo -n " gnome-screensaver"
}

Config ()
{
	# Disabling to lock the screen when the screensaver goes active.
	sudo -u "${LIVE_USERNAME}" dbus-run-session -- gsettings set org.gnome.desktop.screensaver lock-enabled false

	# Creating state file
	touch /var/lib/live/config/gnome-screensaver
}

Cmdline
Init
Config
