#!/bin/sh

. /usr/lib/live/config.sh

## live-config(7) - System Configuration Components
## Copyright (C) 2016-2020 The Debian Live team
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


#set -e

Init ()
{
	# Checking if package is installed
	if ! pkg_is_installed "login" || \
	   component_was_executed "login"
	then
		exit 0
	fi

	echo -n " login"
}

Config ()
{
	# lastlog with autologin doesn't make sense
	sed -i '/^[^#].*pam_lastlog\.so/s/^/# /' /etc/pam.d/login

	# Creating state file
	touch /var/lib/live/config/login
}

Init
Config
