#!/bin/sh

. /usr/lib/live/config.sh

## live-config(7) - System Configuration Components
## Copyright (C) 2016-2020 The Debian Live team
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
## Copyright (C) 2025 MiniOS <https://minios.dev>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.

#set -e

Cmdline ()
{
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.ssh-permit-root-login=*|ssh-permit-root-login=*)
				LIVE_SSH_PERMIT_ROOT_LOGIN="${_PARAMETER#*ssh-permit-root-login=}"
				;;
			live-config.ssh-password-authentication=*|ssh-password-authentication=*)
				LIVE_SSH_PASSWORD_AUTHENTICATION="${_PARAMETER#*ssh-password-authentication=}"
				;;
		esac
	done
}

Init ()
{
	# Checking if package is installed or already configured
	if ! pkg_is_installed "openssh-server" || \
	   component_was_executed "openssh-server"
	then
		exit 0
	fi

	echo -n " openssh-server"
}

Config ()
{
	case "${LIVE_SSH_PERMIT_ROOT_LOGIN}" in
		""|true|false) ;;
		*) LIVE_SSH_PERMIT_ROOT_LOGIN="" ;;
	esac
	case "${LIVE_SSH_PASSWORD_AUTHENTICATION}" in
		""|true|false) ;;
		*) LIVE_SSH_PASSWORD_AUTHENTICATION="" ;;
	esac

	for _PROTOCOL in dsa rsa ecdsa ed25519
	do
		if [ ! -e /etc/ssh/ssh_host_${_PROTOCOL}_key ] &&
		   grep -qs ssh_host_${_PROTOCOL}_key /etc/ssh/sshd_config
		then
			ssh-keygen -q -f /etc/ssh/ssh_host_${_PROTOCOL}_key -N "" -t ${_PROTOCOL}

			_SSH="true"
		fi
	done

	if [ -n "${LIVE_SSH_PERMIT_ROOT_LOGIN}" ] || [ -n "${LIVE_SSH_PASSWORD_AUTHENTICATION}" ]
	then
		mkdir -p /etc/ssh/sshd_config.d
		{
			echo "# Managed by MiniOS live-config"
			case "${LIVE_SSH_PERMIT_ROOT_LOGIN}" in
				true) echo "PermitRootLogin yes" ;;
				false) echo "PermitRootLogin no" ;;
			esac
			case "${LIVE_SSH_PASSWORD_AUTHENTICATION}" in
				true) echo "PasswordAuthentication yes" ;;
				false) echo "PasswordAuthentication no" ;;
			esac
		} > /etc/ssh/sshd_config.d/minios.conf

		if [ -f /etc/ssh/sshd_config ] && ! grep -qs '^Include[[:space:]]\+/etc/ssh/sshd_config.d/\*.conf' /etc/ssh/sshd_config
		then
			printf '\nInclude /etc/ssh/sshd_config.d/*.conf\n' >> /etc/ssh/sshd_config
		fi
		_SSH="true"
	fi

	case "${_SSH}" in
		true)
			# Creating state file
			touch /var/lib/live/config/openssh-server
			;;
	esac
}

Cmdline
Init
Config
