#!/bin/sh

. /usr/lib/live/config.sh

## live-config(7) - System Configuration Components
## Copyright (C) 2016-2020 The Debian Live team
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
## Copyright (C) 2025 MiniOS <https://minios.dev>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.

#set -e

Cmdline ()
{
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.ssh-permit-root-login=*|ssh-permit-root-login=*)
				LIVE_SSH_PERMIT_ROOT_LOGIN="${_PARAMETER#*ssh-permit-root-login=}"
				;;
			live-config.ssh-password-authentication=*|ssh-password-authentication=*)
				LIVE_SSH_PASSWORD_AUTHENTICATION="${_PARAMETER#*ssh-password-authentication=}"
				;;
		esac
	done
}

Init ()
{
	# Checking if package is installed or already configured
	if ! pkg_is_installed "openssh-server" || \
	   component_was_executed "openssh-server"
	then
		exit 0
	fi

	echo -n " openssh-server"
}

Config ()
{
	case "${LIVE_SSH_PERMIT_ROOT_LOGIN}" in
		""|true|false) ;;
		*) LIVE_SSH_PERMIT_ROOT_LOGIN="" ;;
	esac
	case "${LIVE_SSH_PASSWORD_AUTHENTICATION}" in
		""|true|false) ;;
		*) LIVE_SSH_PASSWORD_AUTHENTICATION="" ;;
	esac

	for _PROTOCOL in dsa rsa ecdsa ed25519
	do
		if [ ! -e /etc/ssh/ssh_host_${_PROTOCOL}_key ] &&
		   grep -qs ssh_host_${_PROTOCOL}_key /etc/ssh/sshd_config
		then
			ssh-keygen -q -f /etc/ssh/ssh_host_${_PROTOCOL}_key -N "" -t ${_PROTOCOL}

			_SSH="true"
		fi
	done

	if [ -n "${LIVE_SSH_PERMIT_ROOT_LOGIN}" ] || [ -n "${LIVE_SSH_PASSWORD_AUTHENTICATION}" ]
	then
		_SSH_POLICY="$(
			{
			echo "# Managed by MiniOS live-config"
			case "${LIVE_SSH_PERMIT_ROOT_LOGIN}" in
				true) echo "PermitRootLogin yes" ;;
				false) echo "PermitRootLogin no" ;;
			esac
			case "${LIVE_SSH_PASSWORD_AUTHENTICATION}" in
				true) echo "PasswordAuthentication yes" ;;
				false) echo "PasswordAuthentication no" ;;
			esac
			}
		)"

		_TMP="$(mktemp /etc/ssh/.sshd_config.minios.XXXXXX)" || exit 1
		trap '[ -z "${_TMP:-}" ] || rm -f -- "${_TMP}"' 0 HUP INT TERM
		{
			echo "# BEGIN MiniOS live-config SSH policy"
			printf '%s\n' "${_SSH_POLICY}"
			echo "# END MiniOS live-config SSH policy"
			sed -e '/^# BEGIN MiniOS live-config SSH policy$/,/^# END MiniOS live-config SSH policy$/d' \
				-e '/^# BEGIN MiniOS security profile$/,/^# END MiniOS security profile$/d' \
				/etc/ssh/sshd_config
		} > "${_TMP}" || exit 1

		_SSH_VERSION="$(dpkg-query -W -f='${Version}' openssh-server 2>/dev/null || true)"
		if [ -z "${_SSH_VERSION}" ] || ! dpkg --compare-versions "${_SSH_VERSION}" ge '1:8.2p1~'
		then
			sed -i '/^Include[[:space:]]\+\/etc\/ssh\/sshd_config\.d\/\*\.conf$/d' "${_TMP}" || exit 1
		fi

		chmod --reference=/etc/ssh/sshd_config "${_TMP}" || exit 1
		chown --reference=/etc/ssh/sshd_config "${_TMP}" || exit 1
		/usr/sbin/sshd -t -f "${_TMP}" || exit 1
		mv -f "${_TMP}" /etc/ssh/sshd_config || exit 1
		_TMP=""
		trap - 0 HUP INT TERM
		rm -f /etc/ssh/sshd_config.d/minios.conf
		_SSH="true"
	fi

	case "${_SSH}" in
		true)
			# Creating state file
			touch /var/lib/live/config/openssh-server
			;;
	esac
}

Cmdline
Init
Config
