#!/bin/sh

. /usr/lib/live/config.sh

## live-config(7) - System Configuration Components
## Copyright (C) 2016-2020 The Debian Live team
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


#set -e

Cmdline ()
{
	# Reading kernel command line
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
			live-config.lockscreen-mode=*|lockscreen-mode=*)
				LIVE_LOCKSCREEN_MODE="${_PARAMETER#*lockscreen-mode=}"
				;;
		esac
	done
}

Init ()
{
	# Checking if package is installed or already configured
	if ! pkg_is_installed "xscreensaver" || \
	   component_was_executed "xscreensaver"
	then
		exit 0
	fi

	echo -n " xscreensaver"
}

Config ()
{
	case "${LIVE_LOCKSCREEN_MODE}" in
		hardened)
			if [ -f "/home/${LIVE_USERNAME}/.xscreensaver" ]
			then
				sed -i 's|^lock:.*|lock: True|' "/home/${LIVE_USERNAME}/.xscreensaver"
			else
				echo "lock: True" >> "/home/${LIVE_USERNAME}/.xscreensaver"
			fi
			touch /var/lib/live/config/xscreensaver
			exit 0
			;;
	esac

	if ! grep -qs '^lock:' "/home/${LIVE_USERNAME}/.xscreensaver"
	then
		echo "lock: False" >> "/home/${LIVE_USERNAME}/.xscreensaver"
	fi

	# Creating state file
	touch /var/lib/live/config/xscreensaver
}

Cmdline
Init
Config
